[build]
  command = "cd frontend && npm ci && npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "frontend/dist"
  functions = "netlify/functions"
