[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9.8.1"
  PYTHON_VERSION = "3.9"

[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"
  functions = "../netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  functions = "../netlify/functions"
